### ISSUE TITLE
SOURCE CODE RELEASE

### ISSUE THREAD

**Issue by wjj19950828** [cmsflash/global-context-module#1]
hello! I just can't find the code or INDTALL.md, only readme

thank U!

**Comment by cmsflash** [comment]
Hi wjj,

I am sorry that source code release is still pending patent application. What is especially difficult about our case is that I have left Tencent and therefore have little control over how fast that process goes. When our open source is ready, I will notify you.

**Comment by cmsflash** [comment]
I forgot to mention that, if you do not need the training code and simply want our module, then it will be relatively easy to modify https://github.com/cmsflash/efficient-attention to be an implementation for the global context module.
