### ISSUE TITLE
how to do pre-training transformations

### ISSUE THREAD

**Issue by huxiaotaostasy** [cmsflash/global-context-module#2]
A synthetic clip containing three frames is then generated using image transformations.You did all the transformations,such as rotatiion,TPS,cropping and scaling , on just one frame, and regarded the result frame as one frame of the clip, or you did those transformations separately on different frames and regarded them as the frames of the clip?
I have trained the network which i implemented by myself without pre-training, however, the J&F never reached 60 .So i also wanna ask whether the pretraining has such a big difference in the final model i get. Or, just because I did a bad job in implementing the network.
Thanks!

**Comment by cmsflash** [comment]
The pretraining is done using image datasets, so we apply different transformation to the same image and make a fake video clip.

Pretraining is necessary due to the limited size of the datasets for this task.

**Comment by huxiaotaostasy** [comment]
请问在pre-train之后，还是出现了如附件中的情况怎么办。。困扰我许久了。
May I ask how to solve this kind of problem? DAVIS2016 breakdance




------------------&nbsp;Original&nbsp;------------------

**Comment by cmsflash** [comment]
I did not see any attachment. What problem are you facing?

**Comment by huxiaotaostasy** [comment]
我pretrain之后，然后微调了。都按照论文里面的步骤做的。但是跑DAVIS16的时候，他把breakdance里面所有的人都分割出来了，而不是做动作的人，感觉是以前mask的信息没用上，不知道如何解决。



---Original---

**Comment by cmsflash** [comment]
你在YouTube-VOS上的结果是正常的吗？

**Comment by huxiaotaostasy** [comment]
唔，我一开始把所有物体都弄到模型里面了。最后发现模型是单物体的，然后目前就只跑了DAVIS16。然后我也尝试过按照STM那样写多物体，然后训（没有pre train，是Davis17和YouTubevos 按照5：1混合训的），最好的结果是J&amp;F 58。如果只训单物体的，一直做不好。



---Original---

**Comment by cmsflash** [comment]
最好检查一下训练数据的预处理。

另外我们都是先在YouTube-VOS上预训练的。整体流程是图片数据集、YouTube-VOS、DAVIS，三阶段训练。
