### ISSUE TITLE
About training setting.

### ISSUE THREAD

**Issue by Limingxing00** [cmsflash/global-context-module#3]
Hi,

Have you evaluated the DAVIS 2017  joining youtube-vos? After adding youtube-vos,  could the global-context-module be similar to the effect of STM memory bank? Thank you !

**Comment by cmsflash** [comment]
You may refer to Table 6 in our paper. As it shows, the performance difference between GC and STM is not due to the modules, but due to difference in the evaluation protocols. When following the same protocol, GC performs similarly as STM.
